name: RhemaJoy Ministries
favicon: null
layout_spectrum: 0.3179930769838393
typography_spectrum: 0.4884989126585424
title: RhemaJoy Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3554799435660243
  lightness: 0.6166828216519207
  saturation: 0.48629025695845485
  rhythmicContrast: 0.0093050601426512
purpose: []
