name: K.L. Dunkin
favicon: null
layout_spectrum: 0.3179930769838393
typography_spectrum: 0.4884989126585424
title: RhemaJoy Ministries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7e7e8'
    - '#fe9fbd'
    - '#480f16'
    - '#ff2f45'
    - '#604e36'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.0093050601426512
purpose: []
